# Generated by Django 4.2.16 on 2024-10-12 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mall',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loc_id',
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Admin.location')),
                ('mall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
