# Generated by Django 4.2.16 on 2024-10-15 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_mall_customer_user_remove_customer_loc_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingslot',
            old_name='mall_id',
            new_name='mall',
        ),
        migrations.AddField(
            model_name='rate',
            name='mall',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mall',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
