# Generated by Django 4.2.16 on 2024-10-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mall',
        ),
    ]
