# Generated by Django 4.2.16 on 2024-10-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_alter_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='is_occupied',
            field=models.IntegerField(default=0),
        ),
    ]
