# Generated by Django 4.2.16 on 2024-12-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_alter_parkingslot_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='location',
            field=models.IntegerField(),
        ),
    ]
