# Generated by Django 4.2.16 on 2025-02-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_parkingslot_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='lat',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mall',
            name='lon',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
