# Generated by Django 4.2.16 on 2025-03-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_mall_lat_mall_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mall',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='lon',
        ),
    ]
