# Generated by Django 4.2.16 on 2024-12-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(default='', upload_to='QR/'),
            preserve_default=False,
        ),
    ]
