# Generated by Django 4.2.16 on 2024-12-26 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_parkingslot_location'),
        ('User', '0002_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='parking_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='Admin.parkingslot'),
        ),
    ]
