# Generated by Django 4.2.16 on 2025-02-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_booking_paid_amount_alter_booking_parking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
    ]
